config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get  'dupa' => 'home#dupa'
  get 'majonez' => 'home#majonez'
 
  resources :vegetables, :only => [:create]
end

app/models/vegetable.rb
class Vegetable < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @vegetable = Vegetable.new
  end

  def dupa
  end

  def majonez
  end
end

app/controllers/vegetables_controller.rb
class VegetablesController < ApplicationController

  def create 
    Vegetable.create(params[:vegetable].permit(:name, :vegetable_type, :description))

    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/dupa.html.erb
cokolwiek

app/views/home/index.html.erb
<%= link_to 'dupa', dupa_url %><br>
<%= link_to 'majonez', majonez_url %>

<p>
  <%= form_for @vegetable do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :vegetable_type %>
    <%= f.text_field :vegetable_type %>
    <%= f.label :description %>
    <%= f.text_field :description %>
    <%= f.submit %>
  <% end %>
</p>

<p>
  <ul>
    <% Vegetable.all.each do |warzywo| %>
      <li><%= warzywo.inspect %></li>
    <% end %> 
  </ul>
</p>

app/views/home/majonez.html.erb
i kepucz

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pomidor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>